
[window]

opacity = 1

padding.x = 5
padding.y = 5
dimensions.columns = 140
dimensions.lines = 40
startup_mode = "Windowed"
decorations = "buttonless"

[scrolling]
history = 2000


[general]

import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[font.normal]
family = "UbuntuMono Nerd Font"

[font] 
size = 15

[env]
TERM = "xterm-256color"

[keyboard]
bindings = [
  { key = "D", mods = "Control|Shift", action = "Quit"},
  { key = "N", mods = "Control|Shift", action = "CreateNewWindow" } 
]

[terminal]

[terminal.shell]
program = "tmux"
